apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
       containers:
      - image: akhil2715/my-node-app:latest
        name: my-node-app
        env:
          - name: PORT
            value: '3000'
        securityContext:
          capabilities:
            drop:
              - ALL
          runAsUser: 1015880000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        ports:
          - name: user-port
            containerPort: 3000
            protocol: TCP
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  selector:
    app: spring-boot-app
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: spring-boot-app-route
spec:
  to:
    kind: Service
    name: spring-boot-app-service
  port:
    targetPort: 3000
