apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: akhil2715/my-node-app:prod
          ports:
            - containerPort: 3000
          env:
            - name: ENV_VARIABLE_1
              value: value1
            - name: ENV_VARIABLE_2
              value: value2
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nodejs-app-route
spec:
  to:
    kind: Service
    name: nodejs-app-service
    weight: 100
  port:
    targetPort: 3000
