apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nodejs
  labels:
    app: sample-nodejs
spec:
  selector:
    matchLabels:
      app: sample-nodejs
  template:
    metadata:
      labels:
        app: sample-nodejs
    spec:
      containers:
        - image: akhil2715/my-node-app:prod
          name: nodejs-api
          imagePullPolicy: Always
          ports:
            - name: http-port-3000
              containerPort: 3000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sample-nodejs-service
spec:
  ports:
    - name: http-port-80
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: sample-nodejs
  type: NodePort
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: akhil
spec:
  path: /
  to:
    kind: Service
    name: sample-nodejs-service
  port:
    targetPort: 3000
